language: node_js
dist: trusty
sudo: required

node_js:
  - "6.9.1"

script:
  - ./publish.sh

deploy:
- provider: pages
  local-dir: _book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
